# Generated by Django 3.0.5 on 2020-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_major', models.CharField(max_length=100)),
                ('m_age', models.IntegerField(default=0)),
                ('m_grade', models.IntegerField(default=0)),
                ('m_gender', models.CharField(max_length=30)),
            ],
        ),
    ]
